// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANf6O_HK4O5uOSmTKHEc06-Z3yTZlR1iw',
    appId: '1:567914156523:web:37b49ad43bd407463649ae',
    messagingSenderId: '567914156523',
    projectId: 'doclink-488e7',
    authDomain: 'doclink-488e7.firebaseapp.com',
    storageBucket: 'doclink-488e7.firebasestorage.app',
    measurementId: 'G-QBF5MPXE64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZZGNG8qthcs0fKDM75C1hEun57cp-qY',
    appId: '1:567914156523:android:e7b46a98616454e63649ae',
    messagingSenderId: '567914156523',
    projectId: 'doclink-488e7',
    storageBucket: 'doclink-488e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7e7eVYuhaY7PEm5_kGC8dObAnniHp24',
    appId: '1:567914156523:ios:0ca0f6e74e24df6e3649ae',
    messagingSenderId: '567914156523',
    projectId: 'doclink-488e7',
    storageBucket: 'doclink-488e7.firebasestorage.app',
    iosBundleId: 'com.shogot.doclink',
  );
}
